# Generated by Django 3.0.2 on 2020-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='audio',
            field=models.FileField(default='audios/default.mp3', upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(default='images/level1.jpg', upload_to='images'),
        ),
    ]
